"use strict";
let hello = 'Hello';
let owu = 'owu';
let com = 'com';
let ua = 'ua';
let num_1 = 1;
let num_2 = 10;
let num_3 = -999;
let num_4 = 123;
let num_5 = 3.14;
let num_6 = 2.7;
let num_7 = 16;
let bl_1 = true;
let bl_2 = false;
console.log(hello);
console.log(owu);
console.log(com);
console.log(ua);
console.log(num_1);
console.log(num_2);
console.log(num_3);
console.log(num_4);
console.log(num_5);
console.log(num_6);
console.log(num_7);
console.log(bl_1);
console.log(bl_2);
